In [1]:
import pandas as pd
import numpy as np

import sklearn

In [2]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,LabelEncoder
import pickle

In [3]:
#first step load your file
data=pd.read_csv('/Users/riteshchaudhary/Downloads/CONSULTANCY/DEEP_Learning_project_01/Churn_Modelling.csv')
data.head(5)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [4]:
#feature droping delete unessential columns
data=data.drop(['RowNumber'	,'CustomerId','Surname'],axis=1)
data.head(5)

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [5]:
#ENCODE CATEGORICAL COLUMNS Eg: geography and gender
lable_encoder_gender=LabelEncoder()
data['Gender']=lable_encoder_gender.fit_transform(data['Gender'])
data.head(4)

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0

In [6]:
#ENCODE GEOGRAPY INTO NUMERIC BY USING ONEHOT ENCODER IT CONTERT TEXT VALUES BETWEEN 0 TO 1 NOT ONLY O OR 1
'''from sklearn.preprocessing import OneHotEncoder
onehotencode_geograpy=OneHotEncoder()
data['Geography']=onehotencode_geograpy.fit_transform(data['Geography'])
data.head(100)
#data['Gender'].values'''

"from sklearn.preprocessing import OneHotEncoder\nonehotencode_geograpy=OneHotEncoder()\ndata['Geography']=onehotencode_geograpy.fit_transform(data['Geography'])\ndata.head(100)\n#data['Gender'].values"

In [7]:
from sklearn.preprocessing import OneHotEncoder
import pandas as pd

# Create encoder
onehot = OneHotEncoder()

# Fit & transform
geo_encoded = onehot.fit_transform(data[['Geography']]).toarray()

# Convert into DataFrame
geo_encoded_df = pd.DataFrame(
    geo_encoded,
    columns=onehot.get_feature_names_out(['Geography'])
)

# Drop old column and join new columns
data = pd.concat([data.drop('Geography', axis=1), geo_encoded_df], axis=1)

data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [8]:
import pickle

# Save LabelEncoder
with open('label_encoder_gender.pkl', 'wb') as f:
    pickle.dump(lable_encoder_gender, f)

# Save OneHotEncoder
with open('onehot_encoder_geo.pkl', 'wb') as f:
    pickle.dump(onehot, f)

In [9]:
# DEVIDE DATA INTO INDEPENDENT AND DEPENDENT FEATURE
## Indpendent and dependent features

from sklearn.model_selection import train_test_split# 2d dataframe
X = data.drop(['Exited'], axis=1)  # 1 d dataframe
y = data['Exited']

In [10]:
#TRAIN TEST SPLIT
X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=42,test_size=.20)

#SCALE THESE FEATURES
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

#SAVE PICKLE FILE FRO SCALE DATA
with open('scaler.pkl', 'wb') as f:
    pickle.dump(scaler, f)

ANN MODEL

In [11]:

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime
''' tensorflow as tf → main deep learning library
Sequential → model type (layer-by-layer network)
Dense → fully connected layer (ANN neuron layer)
EarlyStopping → stops training when no improvement
TensorBoard → visualize training (graphs, loss)
datetime → used to create log folder name'''

' tensorflow as tf → main deep learning library\nSequential → model type (layer-by-layer network)\nDense → fully connected layer (ANN neuron layer)\nEarlyStopping → stops training when no improvement\nTensorBoard → visualize training (graphs, loss)\ndatetime → used to create log folder name'

    BUILD MODEL

In [12]:
(X_train.shape[1],)

(12,)

In [13]:
model = Sequential([#Create ANN model (layer-by-layer)
    Dense(64, activation='relu', input_shape=(X_train.shape[1],)),#FIRST HIDDEN  LAYER #64=64 NUERON
    Dense(32, activation='relu'),#SECOND HIDDEN LAYER
    Dense(1, activation='sigmoid')#OUTPUT LAYER #1 neuron → binary classification
                                                #sigmoid → output between 0–1
])

2026-03-24 19:35:26.960946: I metal_plugin/src/device/metal_device.cc:1154] Metal device set to: Apple M1
2026-03-24 19:35:26.960986: I metal_plugin/src/device/metal_device.cc:296] systemMemory: 8.00 GB
2026-03-24 19:35:26.960993: I metal_plugin/src/device/metal_device.cc:313] maxCacheSize: 2.67 GB
2026-03-24 19:35:26.961046: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:306] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2026-03-24 19:35:26.961079: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:272] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)

In [14]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 64)                832

 dense_1 (Dense)             (None, 32)                2080

 dense_2 (Dense)             (None, 1)                 33

=================================================================
Total params: 2945 (11.50 KB)
Trainable params: 2945 (11.50 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [15]:
#OPTIMISER +LOSS
import tensorflow

opt = tensorflow.keras.optimizers.Adam(learning_rate=0.01)
loss = tensorflow.keras.losses.BinaryCrossentropy()

WARNING:absl:At this time, the v2.11+ optimizer `tf.keras.optimizers.Adam` runs slowly on M1/M2 Macs, please use the legacy Keras optimizer instead, located at `tf.keras.optimizers.legacy.Adam`.

In [16]:
#COMPILE THE MODEL
model.compile(optimizer=opt, loss='binary_crossentropy', metrics=['accuracy'])

In [17]:
#TENSOR FLOW SETUP
from tensorflow.keras.callbacks import TensorBoard
import datetime

log_dir = "logs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")

tensorboard_callback = TensorBoard(log_dir=log_dir, histogram_freq=1)

In [18]:
#EARLY STOPPING
from tensorflow.keras.callbacks import EarlyStopping

early_stopping_callback = EarlyStopping(
    monitor='val_loss',
    patience=5,
    restore_best_weights=True
)

In [19]:
# TRAIN THE MODEL
history = model.fit(
    X_train, y_train,
    validation_data=(X_test, y_test),
    epochs=100,
    callbacks=[tensorboard_callback, early_stopping_callback]
)

Epoch 1/100

2026-03-24 19:35:28.195250: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:117] Plugin optimizer for device_type GPU is enabled.
2026-03-24 19:35:28.220920: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:961] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node Adam/AssignAddVariableOp.

250/250 [==============================] - 4s 6ms/step - loss: 0.5652 - accuracy: 0.7790 - val_loss: 0.9310 - val_accuracy: 0.7110
Epoch 2/100
250/250 [==============================] - 1s 5ms/step - loss: 1.0148 - accuracy: 0.7448 - val_loss: 1.2565 - val_accuracy: 0.7555
Epoch 3/100
250/250 [==============================] - 1s 5ms/step - loss: 2.4951 - accuracy: 0.7249 - val_loss: 2.9569 - val_accuracy: 0.7465
Epoch 4/100
250/250 [==============================] - 1s 5ms/step - loss: 4.8668 - accuracy: 0.7214 - val_loss: 8.6086 - val_accuracy: 0.8085
Epoch 5/100
250/250 [==============================] - 1s 5ms/step - loss: 7.2350 - accuracy: 0.7395 - val_loss: 2.5777 - val_accuracy: 0.7955
Epoch 6/100
250/250 [==============================] - 1s 5ms/step - loss: 7.9220 - accuracy: 0.7359 - val_loss: 13.7039 - val_accuracy: 0.6615

In [20]:
#SAVE MODEL
model.save('model.h5')

/Users/riteshchaudhary/Downloads/CONSULTANCY/DEEP_Learning_project_01/venv/lib/python3.10/site-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(

In [21]:
#TENSOR BOARD
%load_ext tensorboard
%tensorboard --logdir logs/fit

ERROR: Failed to launch TensorBoard (exited with 1).
Contents of stderr:
Traceback (most recent call last):
  File "/Users/riteshchaudhary/Downloads/CONSULTANCY/DEEP_Learning_project_01/venv/bin/tensorboard", line 3, in <module>
    from tensorboard.main import run_main
  File "/Users/riteshchaudhary/Downloads/CONSULTANCY/DEEP_Learning_project_01/venv/lib/python3.10/site-packages/tensorboard/main.py", line 27, in <module>
    from tensorboard import default
  File "/Users/riteshchaudhary/Downloads/CONSULTANCY/DEEP_Learning_project_01/venv/lib/python3.10/site-packages/tensorboard/default.py", line 30, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'

In [22]:
%reload_ext tensorboard

In [23]:


import sys
print(sys.executable)

/Users/riteshchaudhary/Downloads/CONSULTANCY/DEEP_Learning_project_01/venv/bin/python